### ISSUE TITLE
Ubuntu issue

### ISSUE THREAD

**Issue by p4ul** [martinssipenko/SublimeHostsEdit#3]
Hi, 

I'm getting this issue on Ubuntu when I try and run the command.

``` Python
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./SublimeHostsEdit.py", line 7, in run
Boost.Python.ArgumentError: Python argument types in
    Window.open_file(Window, NoneType)
did not match C++ signature:
    open_file(SP<edit_window::reference>, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, unsigned int)
    open_file(SP<edit_window::reference>, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >)
```

**Comment by robwala** [comment]
Running on Windows, Sublime Text 3 - works after installing but after sublime is restarted, attempting to run generates:
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "C:\Users\bob.walasek\AppData\Roaming\Sublime Text 3\Installed Packages\HostsEdit.sublime-package\SublimeHostsEdit.py", line 7, in run
  File "C:\Program Files\Sublime Text 3\sublime.py", line 217, in open_file
    return View(sublime_api.window_open_file(self.window_id, fname, flags))
TypeError: String required
